prepare for 2.0.0 release
hpe-storage/co-deployments pull request #254
Opened 2021-06-14 18:24 UTC by raunakkumar

- update yaml files image tags
- update helm release tag and package
- update operator types definitions and crd

Signed-off-by: Raunak <raunak.kumar@hpe.com>

2021-06-14 18:33 UTC, datamattsson requested changes

2021-06-14 18:33 UTC, datamattsson commented on docs/index.yaml
> +      artifacthub.io/prerelease: "true"
false

2021-06-14 18:52 UTC, c-snell approved these changes
After changes requested by @datamattsson, LGTM

2021-06-15 00:16 UTC, datamattsson approved these changes

2021-06-15 05:27 UTC, merged