Con-2149
hpe-storage/co-deployments pull request #302
Opened 2022-03-23 09:54 UTC by bhagyashree-sarawate

@raunakkumar 
Following attributes should be configurable : 
CSP - labels, tolerations, affinity, node selectors

Controller - labels, tolerations, affinity, node selectors

CSI Node - labels, tolerations, affinity, node 

feature page link 
https://confluence.eng.nimblestorage.com/display/ESI/CON-2149

2022-03-29 18:54 UTC, datamattsson requested changes

2022-03-30 07:27 UTC, bhagyashree-sarawate commented on operators/hpe-csi-operator/deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml
> +    labels: { }
done

2022-04-01 10:03 UTC, bhagyashree-sarawate commented on operators/hpe-csi-operator/deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml
> +    labels: { }
@raunakkumar @datamattsson can you please review this PR?

2022-04-06 05:03 UTC, raunakkumar approved these changes

2022-04-06 05:37 UTC, bhagyashree-sarawate commented on operators/hpe-csi-operator/deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml
> +    labels: { }
@datamattsson , i have addressed review comments. Let me know if anything is pending from my side

2022-04-14 17:09 UTC, datamattsson approved these changes

2022-04-18 04:32 UTC, bhagyashree-sarawate commented
@Raunak, @datamattsson , when we can merge this, should I add the pre-release tag?

2022-04-18 04:44 UTC, merged

2022-04-18 04:45 UTC, raunakkumar commented
> @raunak, @datamattsson , when we can merge this, should I add the pre-release tag?

I have merged it. Once it has gone through a round of internal testing we can mark with a pre-release tag