Release readiness for 2.2.0
hpe-storage/co-deployments pull request #314
Opened 2022-07-14 12:20 UTC by bhagyashree-sarawate

Modified all beta tags to 2.2.0
Made prerelease: false
Modified operator-framework 1.22.1
Updated readme for new parameters 
Pending :
Creating package (Once all OK , will create package and then merge)

2022-07-14 16:38 UTC, datamattsson requested changes
According to the internal TOI we're not supporting K8s 1.20 with CSI driver 2.2.

Is there a recent we never pickup latest upstream of SIG storage images for new releases?

2022-07-14 16:38 UTC, datamattsson commented on yaml/csi-driver/v2.2.0/hpe-csi-k8s-1.24.yaml
> +          image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
v1.5.0 is latest

2022-07-19 04:54 UTC, pavansshanbhag commented
@datamattsson  - The existing SIGSTORAGE images that we use do not have any security vulnerabilities. The current user story scope is to incorporate the security vulnerabilities fixes. The QA team has already gone through detailed regression uptill this point and this calls for avoiding adding new things (SIGSTORAGE images) which may(or may not) cause regression. We should have upgraded the SIGSTORAGE image versions the next time, before we start the regression testing. 
For now, we may not be able to pick this for 2.2 release. We will incorporate this as the first thing before we start the next release.

2022-07-19 19:54 UTC, datamattsson approved these changes

2022-07-25 14:59 UTC, pavansshanbhag approved these changes

2022-07-26 03:39 UTC, raunakkumar approved these changes

2022-07-26 03:39 UTC, merged