Add option to disable pre-install hook
hpe-storage/co-deployments pull request #399
Opened 2024-09-17 10:00 UTC by wolffberg

When using Argo CD the pre-install hook will cause a deadlock as Argo CD cannot use the `lookup` function from Helm (See https://github.com/argoproj/argo-cd/issues/4331).

This PR introduces a switch to disable the pre-install hook.

2024-09-17 16:32 UTC, datamattsson requested changes
Thank you for your contribution! Please update the README in the chart as well and address the review comments.

2024-09-17 16:32 UTC, datamattsson commented on helm/charts/hpe-csi-driver/values.yaml
> +  disablePreInstallHook: false
This should be in the global scope, not in `.iscsi.disablePreInstallHook` as we might use the pre-install hooks for other other things.

Rename to `.disablePreInstallHooks` (with an `s`).

2024-09-17 16:32 UTC, datamattsson commented on helm/charts/hpe-csi-driver/Chart.yaml
> +version: "2.5.2"
Don't increment the versions, HPE staff will rev this for the next release.

2024-09-18 06:51 UTC, wolffberg commented
Pushed requested changes👷‍♂️

2024-09-19 04:52 UTC, datamattsson requested changes
Could you change the description to:
```
Disable pre-install hooks when the chart is rendered outside of Kubernetes, such as CI/CD systems.
```

2024-09-19 08:09 UTC, wolffberg commented
Changed description 👍

2024-09-19 15:22 UTC, datamattsson approved these changes
Thank you for your contribution. This will be part of the next release of the Helm chart and Operator expected towards the end of the year.

2024-09-19 15:23 UTC, merged